config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "pages#home"

  as :user do
    get 'julien', to: 'devise/sessions#new'
  end

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/profile', to: 'pages#profile'

  resources :pictures


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pictures, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def default_url_options
  { host: ENV["HOST"] || "http://www.juliencomtegaz.com" }
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home, raise: false
  def home
  end

  def about
  end

  def contact
  end

  def profile
    @pictures = Picture.all
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action :set_picture, only: [:show, :edit, :update, :destroy]
    protect_from_forgery with: :null_session

    def index
        @serie_01 = Picture.where("tag = '1'")
        @serie_02 = Picture.where("tag = '2'")
        @serie_03 = Picture.where("tag = '3'")
        @serie_04 = Picture.where("tag = '4'")
        @serie_05 = Picture.where("tag = '5'")
    end

    def show
        serie = Picture.where(tag: @picture.tag)
        picture = serie.index(@picture)
        index_previous = picture - 1
        index_next = picture + 1

        if index_previous >= 0
            @previous = serie[index_previous]
        end
        if serie[index_next]
            @next = serie[index_next]
        end
    end

    def new
        @picture = Picture.new
    end

    def create
        @picture = Picture.new(picture_params)
        @picture.user = current_user
        if @picture.save
            redirect_to profile_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        @picture.update(picture_params)
        if @picture.save
            redirect_to picture_path(@picture)
        else
            render :edit
        end
    end

    def destroy
        @picture.destroy
        redirect_to profile_path
    end

private

    def set_picture
        @picture = Picture.find(params[:id])
    end

    def picture_params
        params.require(:picture).permit(:name, :description, :format, :tag, :author, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115760649-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-115760649-1');
    </script>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500|Rubik:700" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag "application" %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-content">
    <div class="header text-center">
        <h1>
             Inked Magazines – 2016
        </h1>
        <h2>
             Julien Comte-Gaz
        </h2>
    </div>
    <div class="about-text">
        <p>
             Quand l’anthropologue américain Edward T.Hall fait état de la notion de proxémie dans son ouvrage intitulé « <em> La Dimension Cachée (1) </em>», il nous présente une étude sur la distance d’interaction d’échange entre les personnes. Cette distance variant
            de la sphère publique —supérieure à 3,6m quand on parle en public ou que l’on interpelle– à la sphère intime –inférieure
            à 45cm quand l’on chuchote ou que l’on embrasse quelqu’un–.
        </p>
        <p>
             La série Inked Magazines reprend cette notion de proxémie avec pour but d’offrir un double regard sur l’objet, ici une image
            de magazine de charme des années 70, tiré à des milliers d’exemplaires, cet objet commun devient alors unique. L’intervention
            sur l’image par le biais du dessin offre une transition de la sphère publique vers la sphère intime guidant le regard du
            spectateur de ce qui parait être un tache au premier abord vers ce qui est en réalité une composition concentrique à très
            petite échelle. Dans une société ou la rapidité est synonyme de gain, ce travail propose de perturber les codes mettant en
            avant une pratique où le geste répétitif, minutieux, à la lisière d’un comportement compulsif –à l’instar de Roman Opalka
            dont le but a été d’inscrire la trace d’un temps irréversible – permet de mieux cacher pour révéler.
        </p>
        <p>
             Les formes habillant ces corps dénudés sont constitués de milliers de cercles tracés à la main pour un rendu souvent interprété
            comme résultant d’une manipulation informatique bien que ces créations ne soient pas le résultat d’une quelconque machine.
        </p>
        <p>
             Quand Roland Barthes nous expose dans son ouvrage « <em>La Chambre Claire (2)</em>» l’idée du ‘punctum’ –mot latin désignant un petit
            trou, une piqûre, une déchirure – nous pouvons dès lors regarder l’imperfection de ce détail comme le fruit du hasard qui
            guide le regard du spectateur.
        </p>
        <p>
             Inspiré par des artistes tels que Felice Varini ou encore Georges Rousse dont la pratique consiste en partie à imposer un
            seul point de vue ramenant tous les éléments au premier plan par le principe d’anamorphose, la série des Inked Magazines
            avec ses formes quasi-tatoués sur ces corps proposent un point de vue autre au spectateur.
        </p>
        <p>
             Ce travail tente de mettre en péril l’automatisme selon lequel nous sommes conditionnés à passer à autre chose dès lors
            que l’œil n’a pas détecté ce ‘punctum’. Cette série propose un voyage entre les différentes sphères ou l’objet intime devient
            public ou la nudité devient tout à coup socialement plus acceptable.
        </p>
        <p>
            <em>
                 (1) Edward T. Hall, La Dimension cachée [« The Hidden Dimension »], Paris, Seuil, (1re éd. 1971 en français, 1966 en anglais)
                (2) Roland Barthes, La chambre claire : Note sur la photographie, Paris, Seuil, 1980
            </em>
        </p>
    </div>
    <div class="about-img">
        <%= image_tag  "about.jpg" %>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="contact-wrap">
    <div class="contact">
        <h1>
             Contact
        </h1>
        <p>
             Julien Comte-Gaz <br />
             né en 1987 à Adelaide, Australie <br />
            vit et travaille à Paris <br />
            contact : <%= mail_to "hello@juliencomtegaz.com", "hello@juliencomtegaz.com", class: "hover-underline-animation" %>
        </p>
        <%= render 'shared/instagram' %>
    </div>
</div>

app/views/pages/home.html.erb
<div id="picture-home">
    <%= link_to pictures_path do %>
        <%= image_tag  "home.jpg" %>
    <% end %>
</div>

app/views/pages/profile.html.erb
<% if user_signed_in? %>
    <div class="profile-content">
        <div class="settings">
            <ul>
                <li>
                    <%= link_to  "Déconnexion", destroy_user_session_path, method: :delete,class: "btn-sign-out" %>
                </li>
                <li>
                    <%= link_to  "Ajouter une nouvelle photo", new_picture_path, class: "btn-add-photo" %>

                </li>
            </ul>
        </div>
        <div class="gallery">
            <ul>
                <% @pictures.each do |picture| %>
                    <li>
                        <p><%= picture.name %></p>
                        <p><%= cl_image_tag picture.photo, height: 00, width: 200 %></p>
                        <p><%= link_to  "Show", picture_path(picture.id) %>
                        <%= link_to  "Edit", edit_picture_path(picture.id) %>
                        <%= link_to  "Delete", picture_path(picture.id), method: :delete, data: { confirm: "Veux-tu vraiment supprimer cette photo petit chenapan ?" } %></p>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
<% else %>
    <div class="alert-section text-center">
        <h1>Désolé, vous n'êtes pas autorisé à venir par ici.</h1>
        <h2><%= link_to  "Retour sur la page d'accueil", root_path %></h2>
    </div>
<% end %>

app/views/pictures/edit.html.erb
<div class="new-content">
  <div class="new">
    <%= simple_form_for(@picture) do |f| %>
      <%= f.input :name, label: "Nom de la photo" %>
      <%= f.input :description %>
      <%= f.input :format %>
      <%= f.input :author, label: "Artiste" %>
      <%= f.input :tag, as: :radio_buttons, collection: [['1', 'Back in the 1920\'s'], ['2', 'Inked Magazines'], ['3', 'Oculus'], ['4', 'Miscellaneous']], label_method: :second, value_method: :first %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.button :submit, value: "Mettre à jour", class: "btn-primary submit update-btn" %>
    <% end %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="tabs-wrap">
    <ul class="tabs">
        <li class="tab-link current" data-tab="tab-1">Back in the 1920's</li>
		<li class="tab-link" data-tab="tab-2">Inked Magazines</li>
		<li class="tab-link" data-tab="tab-3">Oculus</li>
		<li class="tab-link" data-tab="tab-4">Miscellaneous</li>
		<li class="tab-link" data-tab="tab-5">Pixel series</li>
	</ul>
    <div class="tabs-content">
        <div id="tab-1" class="tab-content current">
            <ul class="grid-container">
                <% @serie_01.each do |picture|%>
                    <li class="grid-container-list">
                        <%= link_to picture_path(picture.id) do %>
                            <%= cl_image_tag picture.photo %>
                            <!-- <p> <%= picture.name %> </p> -->
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
        <div id="tab-2" class="tab-content">
            <ul class="grid-container">
                <% @serie_02.each do |picture|%>
                    <li class="grid-container-list">
                        <%= link_to picture_path(picture.id) do %>
                            <%= cl_image_tag picture.photo %>
                            <!-- <p> <%= picture.name %> </p> -->
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
        <div id="tab-3" class="tab-content">
            <ul class="grid-container">
                <% @serie_03.each do |picture|%>
                    <li class="grid-container-list">
                        <%= link_to picture_path(picture.id) do %>
                            <%= cl_image_tag picture.photo %>
                            <!-- <p> <%= picture.name %> </p> -->
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
        <div id="tab-4" class="tab-content">
            <ul class="grid-container">
                <% @serie_04.each do |picture|%>
                    <li class="grid-container-list">
                        <%= link_to picture_path(picture.id) do %>
                            <%= cl_image_tag picture.photo %>
                            <!-- <p> <%= picture.name %> </p> -->
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
        <div id="tab-5" class="tab-content">
            <ul class="grid-container">
                <% @serie_05.each do |picture|%>
                    <li class="grid-container-list">
                        <%= link_to picture_path(picture.id) do %>
                            <%= cl_image_tag picture.photo %>
                            <!-- <p> <%= picture.name %> </p> -->
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/pictures/new.html.erb
<div class="new-content">
  <div class="new">
    <%= simple_form_for(@picture) do |f| %>
      <%= f.input :name, label: "Nom de la photo" %>
      <%= f.input :description %>
      <%= f.input :format %>
      <%= f.input :author, label: "Artiste" %>
      <%= f.input :tag, as: :radio_buttons, collection: [['1', 'Back in the 1920\'s'],
                                                         ['2', 'Inked Magazines'],
                                                         ['3', 'Oculus'],
                                                         ['4', 'Miscellaneous'],
                                                         ['5', 'Pixel series']], label_method: :second, value_method: :first %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.button :submit, value: "Ajouter une photo", class: "btn-primary submit" %>
    <% end %>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="show-content">
    <div class="back">
        <%= link_to  "Retour", pictures_path %>
    </div>
    <div class="img-show">
        <%= cl_image_tag @picture.photo, class: "img" %>
    </div>
    <div class="definition-show text-center">
        <h1><%= @picture.name %></h1>
        <p><%= @picture.description %></br>
            <%= @picture.format %></br>
            <%= @picture.author %></p>
        <% if user_signed_in? %>
            <p>
                <%= link_to  "Edit", edit_picture_path(@picture.id) %>
                    <%= link_to  "Delete", picture_path(@picture.id), method: :delete, data: { confirm: "Veux-tu vraiment supprimer cette photo petit chenapan ?" } %>
            </p>
        <% end %>
    </div>
    <div class="pagging">
        <div class="pagging-left">
            <% if @previous %> 
                <%= link_to picture_path(@previous.id) do %>
                    <p>
                        <i class="fas fa-angle-left"></i> <%= @previous.name %>
                    </p>
                <% end %>
            <% end %>
        </div>
        <div class="pagging-right">
            <% if @next %>
                <%= link_to picture_path(@next.id) do %>
                    <p>
                        <%= @next.name %> <i class="fas fa-angle-right"></i>
                    </p>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer>
    <div class="author">
        <p>Site réalisé avec <i class="fas fa-heart"></i> par <%= link_to 'François R.', 'http://www.francoisrabanel.fr', target: "_blank" %></p>
    </div>
</footer>

app/views/shared/_instagram.html.erb
<blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/p/6whAHXx5N-/" data-instgrm-version="8"
    style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
    <div style="padding:8px;">
        <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50.0% 0; text-align:center; width:100%;">
            <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div>
        </div>
        <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">
            <a href="https://www.instagram.com/p/6whAHXx5N-/" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;"
                target="_blank">Une publication partagée par Julien (@juliencomte)</a> le
            <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2015-08-24T07:39:48+00:00">24 Août 2015 à 12 :39 PDT</time>
        </p>
    </div>
</blockquote>
<script async defer src="//www.instagram.com/embed.js">
</script>

app/views/shared/_navbar.html.erb
<div class="grid-navbar">
    <div class="navbar-left">
        <h1>
            <%= link_to  "JULIEN COMTE-GAZ", root_path %>
        </h1>
    </div>
    <% if user_signed_in? %>
    <div class="navbar-right">
            <ul>
                <li>Bonjour
                    <%= link_to profile_path do %> 
                        <%= current_user.email %>
                    <% end %>
                </li>
                <li><%= link_to  "Works", pictures_path %></li>
                <li><%= link_to  "About", about_path %></li>
                <li><%= link_to  "Contact", contact_path %></li>
                <li><%= link_to  "Instagram", "https://www.instagram.com/juliencomte/", target: "_blank" %></li>
            </ul>
        </div>
    <% else %>
        <div class="navbar-right">
            <ul>
                <li><%= link_to  "Works", pictures_path %></li>
                <li><%= link_to  "About", about_path %></li>
                <li><%= link_to  "Contact", contact_path %></li>
                <li><%= link_to  "Instagram", "https://www.instagram.com/juliencomte/", target: "_blank" %></li>
            </ul>
        </div>
    <% end %>
</div>